# Generated by Django 5.0.1 on 2024-02-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('author', models.CharField(blank=True, max_length=254)),
                ('publisher', models.CharField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('edition', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(default='other', max_length=254)),
                ('owner', models.BooleanField()),
                ('location', models.CharField(default='home', max_length=254)),
                ('borrowed_from', models.CharField(blank=True, max_length=254)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibsnail.user')),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
    ]
